name: Deploy FE

on:
  push:
    branches:
      - main

jobs:
  deploy-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete
          path: ./client
          remote_path: ./client
          remote_host: 13.51.48.110
          remote_user: ubuntu
          remote_key: "${{ secrets.DEPLOY_KEY }}"

      - name: Set ownership on remote server
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > private_key.pem
          chmod 600 private_key.pem

          # Create known_hosts file if it doesn't exist
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          
          # Clear old key from known_hosts
          ssh-keygen -R 13.51.48.110 >> /home/runner/.ssh/known_hosts

          # Run the SSH command
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@13.51.48.110 \
          "sudo chown -R ubuntu:apache ./client"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
# test comment
